<script>
	import "../../styles/legal.css";
    import data from "../../utils/data.ts";
</script>

<div class="legal-container">
    <h1 class="font-bold mb-4">Cookie Policy</h1>
    <div class="paragraph">Cookies are small data files that are placed on your computer or mobile device when you visit a website. Cookies are widely used by website owners in order to make their websites work, or to work more efficiently, as well as to provide reporting information.</div>
    <div class="paragraph">Cookies set by the website owner (in this case, Alertbot) are called "first party cookies". Cookies set by parties other than the website owner are called "third party cookies". Third party cookies enable third party features or functionality to be provided on or through the website (e.g. like advertising, interactive content and analytics). The parties that set these third party cookies can recognize your computer both when it visits the website in question and also when it visits certain other websites.</div>
    <div class="paragraph">We use first and third party cookies for several reasons. Some cookies are required for technical reasons in order for our Websites to operate, and we refer to these as "essential" or "strictly necessary" cookies. Other cookies also enable us to track and target the interests of our users to enhance the experience on our Online Properties. Third parties serve cookies through our Websites for advertising, analytics and other purposes. This is described in more detail below.</div>
    <div class="paragraph">You have the right to decide whether to accept or reject cookies. You can exercise your cookie rights by setting your preferences in the Cookie Consent Manager. The Cookie Consent Manager allows you to select which categories of cookies you accept or reject. Essential cookies cannot be rejected as they are strictly necessary to provide you with services.</div>
    <div class="paragraph">The Cookie Consent Manager can be found in the notification banner and on our website. If you choose to reject cookies, you may still use our website though your access to some functionality and areas of our website may be restricted. You may also set or amend your web browser controls to accept or refuse cookies. As the means by which you can refuse cookies through your web browser controls vary from browser-to-browser, you should visit your browser's help menu for more information.</div>
    <div class="paragraph">We may update our Cookie Policy from time to time. Thus, we advise you to review this page periodically for any changes. We will notify you of any changes by posting the new Cookie Policy on this page. These changes are effective immediately, after they are posted on this page.</div>
	<div class="paragraph">If you have questions or comments about this notice, you may email us at <a href="mailto:{data.core.contact.cookies}" class="link">{data.core.contact.cookies}</a>.</div>
</div>