<script>
	import "../../styles/legal.css";
	import data from "../../utils/data";
</script>

<div class="legal-container">
	<h1 class="font-bold mb-4">Privacy Policy</h1>
	<p class="paragraph">Last updated at: {data.legal.privacy.lastUpdated}</p>
	<div class="paragraph"><span class="bold">TL;DR: </span>When you visit the Alertbot website we do not use any cookies and we do not collect any personal data. We use the <a href="https://plausible.io/privacy" class="link" target="_blank" rel="noopener noreferrer">plausible</a> analytics service which does not use cookies. When you log in we store session data in cookies which are necessary so you don't have to log in every time you want to use our service.</div>
	<div class="paragraph">We believe that your privacy is very important and this is why you should feel confident when using our website or submitting your personal data on it. Reading this privacy notice will help you understand your privacy rights and choices. If you do not agree with our policies and practices, please do not use our Services. If you still have any questions or concerns, please contact us at <a href="mailto:{data.core.contact.privacy}" class="link">{data.core.contact.privacy}</a>.</div>
	<div class="paragraph">We collect personal information that you voluntarily provide to us when you express an interest in obtaining information about us or our products and Services, when you participate in activities on the Services, or otherwise when you contact us.</div>
	<div class="paragraph">We may collect data necessary to process your payment if you make purchases, such as your payment instrument number (such as a credit card number), and the security code associated with your payment instrument. All payment data is stored by Stripe. You may find their privacy notice link(s) here: <a href="https://stripe.com/en-gb/privacy" class="link">https://stripe.com/en-gb/privacy</a></div>
	<div class="paragraph">Our Services offer you the ability to register and log in using your third-party social media account details (like your Discord logins). Where you choose to do this, we will receive certain profile information about you from your social media provider. The profile information we receive may vary depending on the social media provider concerned, but will often include your name, email address, friends list, and profile picture, as well as other information you choose to make public on such a social media platform.</div>
	<div class="paragraph">We may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by us. Therefore, we strongly advise you to review the Privacy Policy of these websites. We have no control over, and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services. </div>
	<div class="paragraph">We may update our Privacy Policy from time to time. Thus, we advise you to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately, after they are posted on this page. </div>
	<div class="paragraph">If you have questions or comments about this notice, you may email us at <a href="mailto:{data.core.contact.privacy}" class="link">{data.core.contact.privacy}</a>.</div>
</div>